In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
X = dataset.iloc[:,3:-1].values
Y = dataset.iloc[:,-1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
X.shape

(10000, 10)

In [6]:
print(Y)

[1 0 1 ... 1 1 0]


In [7]:
Y.shape

(10000,)

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [9]:
print(X[:,4])

[0.0 0.0 0.0 ... 0.0 1.0 0.0]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state = 0)
X.shape

(10000, 13)

# feature scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

# importing keras libraries

In [12]:
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# initializing ANN

In [13]:
classifier = Sequential()
 

# adding input layer to the first hidden layer

In [14]:
classifier.add(Dense(7,kernel_initializer = 'glorot_uniform', activation = 'relu', input_dim=13))

# adding second hidden layer

In [15]:
classifier.add(Dense(7,kernel_initializer = 'glorot_uniform', activation = 'relu'))

# Adding output layer

In [16]:
classifier.add(Dense(1,kernel_initializer = 'glorot_uniform', activation = 'sigmoid'))

# Compiling the ANN

In [17]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics=['accuracy'])

# fitting ANN to the training set

In [18]:
classifier.fit(X_train,Y_train,batch_size= 10, epochs=100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 4s 541us/sample - loss: 0.5034 - accuracy: 0.7741
Epoch 2/100
8000/8000 [==============================] - 2s 311us/sample - loss: 0.4343 - accuracy: 0.8066
Epoch 3/100
8000/8000 [==============================] - 2s 301us/sample - loss: 0.4192 - accuracy: 0.8177
Epoch 4/100
8000/8000 [==============================] - 2s 301us/sample - loss: 0.4082 - accuracy: 0.8270
Epoch 5/100
8000/8000 [==============================] - 3s 348us/sample - loss: 0.3975 - accuracy: 0.8321
Epoch 6/100
8000/8000 [==============================] - 3s 327us/sample - loss: 0.3878 - accuracy: 0.8353
Epoch 7/100
8000/8000 [==============================] - 3s 314us/sample - loss: 0.3783 - accuracy: 0.8413
Epoch 8/100
8000/8000 [==============================] - 2s 297us/sample - loss: 0.3703 - accuracy: 0.8451
Epoch 9/100
8000/8000 [==============================] - 3s 317us/sample - loss: 0.3627 - accuracy: 0.8514
Epoch 10/100
80

In [22]:
y_pred =  classifier.predict(X_test)
print(y_pred)

[[0.2217124 ]
 [0.26129085]
 [0.23347065]
 ...
 [0.15975626]
 [0.12311415]
 [0.18117413]]


In [24]:
y_pred = (y_pred>0.5)
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [26]:
y_pred.shape

(2000, 1)

In [34]:
print(y_pred[7])

[False]


In [36]:
np.set_printoptions(threshold=np.inf)

In [39]:
from sklearn.metrics import confusion_matrix

In [41]:
cm=confusion_matrix(Y_test, y_pred)
print(cm)

[[1543   52]
 [ 218  187]]


In [42]:
(1543+187)/2000

0.865